# GoReleaser configuration for Lightfold CLI
# See: https://goreleaser.com/customization/

version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: lightfold
    main: ./cmd/lightfold
    binary: lightfold
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore Windows ARM64 (less common)
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: lightfold-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    builds:
      - lightfold
    rlcp: true
    files:
      - README.md
      - LICENSE*
    formats:
      - tar.gz
      - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Other Changes'
      order: 999

homebrews:
  - name: lightfold
    repository:
      owner: theognis1002
      name: homebrew-lightfold
      # GoReleaser will create this repo automatically on first release
      # Or you can create it manually before running the release
    homepage: https://github.com/theognis1002/lightfold-cli
    description: "Framework detector and deployment tool for web applications"
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "lightfold"
    test: |
      system "#{bin}/lightfold", "--version"

release:
  github:
    owner: theognis1002
    name: lightfold-cli
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install theognis1002/lightfold/lightfold
    ```

    ### Manual Download
    Download the binary for your platform from the assets below.
